### ISSUE TITLE
WINCOMP

### ISSUE THREAD

**Issue by 77377** [DaveBenham/VenomModules#17]
The min and max outputs don't match min or max of the input signals upon casual inspection with a scope.

**Comment by DaveBenham** [comment]
It works perfectly in my hands. It outputs the minimum or maximum value between inputs A and B and a given point in time. It does not compute a minimum or maximum value over time.

If you are not seeing this behavior, then I need to see a screenshot of a patch showing the problem, or better yet, an example patch file that I can test.

Thanks

**Comment by DaveBenham** [comment]
problem never clarified. unable to see any problems in my hands. i suspect there was a misunderstanding of the functionality
